In [165]:
from sklearn import model_selection
import pandas as pd
import numpy as np
##### main custom functions
def one_hot_encode(df,columns_for_one_hot):
    '''One hot encode the columns for feeding into the model
    :df: Dataframe of the data
    :columns_for_one_hot: array name of columns to input
    :return: Dataframe of the one hot encoded data with prefix = columns_for_one_hot
    '''
#     for col_index in columns_for_one_hot:
#         df[col_index]=df[col_index].replace(['0',0], 'No_{}'.format(col_index))
    ## one hot encode
    for column_for_one_hot in columns_for_one_hot:
        #  Get one hot encoding of columns B
        one_hot = pd.get_dummies(df[column_for_one_hot],prefix=column_for_one_hot)
        # Drop column B as it is now encoded
        df = df.drop(column_for_one_hot,axis = 1)
        # Join the encoded df
        df = df.join(one_hot,rsuffix=column_for_one_hot)
    return df

In [166]:
dfg = pd.read_csv(
    './vintage_wine_description_processed.csv',index_col=0).fillna(0)


In [167]:
dfg.head()

country                                        description  \
0     Italy  Aromas include tropical fruit, broom, brimston...   
1  Portugal  This is ripe and fruity, a wine that is smooth...   
2        US  Tart and snappy, the flavors of lime flesh and...   
3        US  Pineapple rind, lemon pith and orange blossom ...   
4        US  Much like the regular bottling from 2012, this...   

                          designation  points  price           province  \
0                        Vulkà Bianco      87    0.0  Sicily & Sardinia   
1                            Avidagos      87   15.0              Douro   
2                                   0      87   14.0             Oregon   
3                Reserve Late Harvest      87   13.0           Michigan   
4  Vintner's Reserve Wild Child Block      87   65.0             Oregon   

              region_1           region_2  \
0                 Etna                  0   
1                    0                  0   
2    Willamette Valley  Willamette Valley   
3  Lake Michigan Shore                  0   
4    Willamette Valley  Willamette Valley   

                                               title         variety  ...  \
0                  Nicosia 2013 Vulkà Bianco  (Etna)     White Blend  ...   
1      Quinta dos Avidagos 2011 Avidagos Red (Douro)  Portuguese Red  ...   
2      Rainstorm 2013 Pinot Gris (Willamette Valley)      Pinot Gris  ...   
3  St. Julian 2013 Reserve Late Harvest Riesling ...        Riesling  ...   
4  Sweet Cheeks 2012 Vintner's Reserve Wild Child...      Pinot Noir  ...   

  taste_long taste_fine taste_creami  taste_medium  taste_dens  taste_make  \
0        0.0        0.0          0.0           0.0         0.0         0.0   
1        0.0        0.0          0.0           0.0         0.0         0.0   
2        0.0        0.0          0.0           0.0         0.0         0.0   
3        0.0        0.0          0.0           0.0         0.0         0.0   
4        0.0        0.0          0.0           0.0         0.0         0.0   

   taste_complex  taste_power  taste_delici  taste_also  
0            0.0          0.0           0.0         0.0  
1            0.0          0.0           0.0         0.0  
2            0.0          0.0           0.0         0.0  
3            0.0          0.0           0.0         0.0  
4            0.0          0.0           0.0         0.0  

[5 rows x 136 columns]

In [168]:
to_encode=['area','country','province','region_1','region_2','variety']
to_drop=['designation','description','title','Location_description','location','winery']
dfg=dfg.drop(to_drop,axis=1)
dfg=one_hot_encode(dfg,to_encode)

In [169]:
dfg.head()

points  price  year   temp1  temp10  temp11  temp12  temp13  temp14  \
0      87    0.0  2013  11.390  20.302  16.792  12.432  11.375   9.663   
1      87   15.0  2011   4.690  12.437   7.362   4.967   5.142   6.502   
2      87   14.0  2013   4.350  11.176   7.606   3.811   2.580   4.904   
3      87   13.0  2013  -1.763  10.034   3.674   1.283  -2.770  -4.096   
4      87   65.0  2012   4.761  10.858   5.631   2.999   4.350   4.755   

   temp15  ...  variety_Yapincak  variety_Zelen  variety_Zibibbo  \
0  13.650  ...                 0              0                0   
1   8.337  ...                 0              0                0   
2   7.617  ...                 0              0                0   
3  -0.363  ...                 0              0                0   
4   5.160  ...                 0              0                0   

   variety_Zierfandler  variety_Zierfandler-Rotgipfler  variety_Zinfandel  \
0                    0                               0                  0   
1                    0                               0                  0   
2                    0                               0                  0   
3                    0                               0                  0   
4                    0                               0                  0   

   variety_Zlahtina  variety_Zweigelt  variety_Çalkarası  variety_Žilavka  
0                 0                 0                  0                0  
1                 0                 0                  0                0  
2                 0                 0                  0                0  
3                 0                 0                  0                0  
4                 0                 0                  0                0  

[5 rows x 2540 columns]

In [170]:
list(dfg.columns)

['points',
 'price',
 'year',
 'temp1',
 'temp10',
 'temp11',
 'temp12',
 'temp13',
 'temp14',
 'temp15',
 'temp16',
 'temp17',
 'temp18',
 'temp19',
 'temp2',
 'temp20',
 'temp21',
 'temp3',
 'temp4',
 'temp5',
 'temp6',
 'temp7',
 'temp8',
 'temp9',
 'latitude',
 'longitude',
 'taste_aroma',
 'taste_fruit',
 'taste_herb',
 'taste_palat',
 'taste_offer',
 'taste_appl',
 'taste_citru',
 'taste_acid',
 'taste_ripe',
 'taste_fruiti',
 'taste_smooth',
 'taste_firm',
 'taste_tannin',
 'taste_juici',
 'taste_red',
 'taste_berri',
 'taste_tart',
 'taste_flavor',
 'taste_lime',
 'taste_green',
 'taste_crisp',
 'taste_lemon',
 'taste_orang',
 'taste_bit',
 'taste_finish',
 'taste_bottl',
 'taste_come',
 'taste_tannic',
 'taste_earthi',
 'taste_herbal',
 'taste_good',
 'taste_blackberri',
 'taste_raspberri',
 'taste_show',
 'taste_mouth',
 'taste_full',
 'taste_bodi',
 'taste_spici',
 'taste_dark',
 'taste_plum',
 'taste_fresh',
 'taste_bright',
 'taste_white',
 'taste_pepper',
 'taste_savori',

# Split XY

In [171]:
ycol=['points','price']
X = dfg.drop(ycol, axis=1) # Training & Validation data
Y = dfg[ycol]              # Response / Target Variable

##golden test
# ycol=['points']
# X = dfg.head(10).drop(ycol, axis=1) # Training & Validation data
# Y = dfg.head(10)[ycol]              # Response / Target Variable

print(X.shape, Y.shape)

# Split training set so that we validate on 20% of the data
# Note that our algorithms will never have seen the validation 

np.random.seed(1337) # set random seed for reproducibility

from sklearn.model_selection import train_test_split

X_train, X_val, Y_train, Y_val = \
                train_test_split(X, Y, test_size=0.2)

print('Training Samples:', X_train.shape, Y_train.shape)
print('Validation Samples:', X_val.shape, Y_val.shape)

# test different model

(125345, 2538) (125345, 2)
Training Samples: (100276, 2538) (100276, 2)
Validation Samples: (25069, 2538) (25069, 2)


In [53]:
#import libs
# No warnings
import warnings
warnings.filterwarnings('ignore') # Filter out warnings

# data analysis and wrangling
import pandas as pd
import numpy as np

# visualization
# import matplotlib.pyplot as plt
# %matplotlib inline
# import seaborn as sns

# machine learning
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB # Gaussian Naive Bays
from sklearn.linear_model import Perceptron
from sklearn.tree import DecisionTreeClassifier

import xgboost as xgb

# from plot_distribution import plot_distribution
# plt.rcParams['figure.figsize'] = (9, 5)

In [65]:
logreg = LogisticRegression()           # create
logreg.fit(X_train, Y_train)            # train
acc_log_2 = logreg.score(X_val, Y_val)  # predict & evaluate

print('Logistic Regression accuracy:',\
      str(round(acc_log_2*100,2)),'%')

Logistic Regression accuracy: 100.0 %


In [66]:
knn = KNeighborsClassifier(n_neighbors = 5)                  # instantiate
knn.fit(X_train, Y_train)                                    # fit
acc_knn = knn.score(X_val, Y_val)                            # predict + evaluate

print('K-Nearest Neighbors labeling accuracy:', str(round(acc_knn*100,2)),'%')                                

K-Nearest Neighbors labeling accuracy: 88.32 %


In [67]:
# Support Vector Machines Classifier (non-linear kernel)
svc = SVC()                                                  # instantiate
svc.fit(X_train, Y_train)                                    # fit
acc_svc = svc.score(X_val, Y_val)                            # predict + evaluate

print('Support Vector Machines labeling accuracy:', str(round(acc_svc*100,2)),'%')

Support Vector Machines labeling accuracy: 91.55 %


In [68]:
perceptron = Perceptron()                                    # instantiate 
perceptron.fit(X_train, Y_train)                             # fit
acc_perceptron = perceptron.score(X_val, Y_val)              # predict + evalaute

print('Perceptron labeling accuracy:', str(round(acc_perceptron*100,2)),'%')

Perceptron labeling accuracy: 87.5 %


In [70]:
# XGBoost, same API as scikit-learn
gradboost = xgb.XGBClassifier(n_estimators=1000)             # instantiate
gradboost.fit(X_train, Y_train)                              # fit
acc_xgboost = gradboost.score(X_val, Y_val)                  # predict + evalute

print('XGBoost labeling accuracy:', str(round(acc_xgboost*100,2)),'%')

KeyboardInterrupt: 

In [54]:
# Random Forest
random_forest = RandomForestClassifier(n_estimators=500)   # instantiate
random_forest.fit(X_train, Y_train)                         # fit
acc_rf = random_forest.score(X_val, Y_val)                  # predict + evaluate

print('Random Forest labeling accuracy:', str(round(acc_rf*100,2)),'%')

ValueError: Unknown label type: 'continuous-multioutput'

In [176]:
ycol=['points','temp1']
regex_out_taste='^(?!taste)'
X = dfg.filter(regex=regex_out_taste).drop(ycol, axis=1) # Training & Validation data
Y = dfg[ycol]              # Response / Target Variable
### normalize data
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
X=scaler.fit_transform(X)
Y=scaler.fit_transform(Y)
# print(Y)

print(X.shape, Y.shape)

# Split training set so that we validate on 20% of the data
# Note that our algorithms will never have seen the validation 

np.random.seed(5875) # set random seed for reproducibility

from sklearn.model_selection import train_test_split

X_train, X_val, Y_train, Y_val = \
                train_test_split(X, Y, test_size=0.2)

print('Training Samples:', X_train.shape, Y_train.shape)
print('Validation Samples:', X_val.shape, Y_val.shape)

# test different model

from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras import optimizers
# Y_train = to_categorical(Y_train)[:,0].squeeze()
model = Sequential()
model.add( Dense(units=2000,kernel_initializer='random_normal' ,activation='relu', input_shape=(1068,) ))
model.add( Dropout(0.5))
model.add( Dense(units=1000, activation='relu'))
model.add( Dropout(0.5))
model.add( Dense(units=500, activation='relu'))
model.add( Dropout(0.5))
model.add( Dense(units=2, activation='tanh') )
optimizer = optimizers.SGD(lr=0.0001, momentum=0.01, decay=0.01, nesterov=False)
model.compile(optimizer='adam',
              loss='mean_squared_error',
              metrics=['mean_squared_error'])
model.fit(X_train, Y_train, epochs = 20, batch_size= 30)
# # Evaluate the model Accuracy on test set
# print('Neural Network accuracy:',str(model.evaluate(X_val,Y_val,batch_size=50,verbose=True)))
print('mean_squared error is:',np.round(model.evaluate(X_val,Y_val,batch_size=50,verbose=True)[1],4)) # predict and evaluate
print(X[21])
# print(model.predict(np.expand_dims(X[21],axis=0),batch_size=1,verbose=1)*100)
print(model.predict(X[40:50,:],batch_size=1,verbose=1)*100)
print(Y[40:50,:]*100)


(125345, 2440) (125345, 2)
Training Samples: (100276, 2440) (100276, 2)
Validation Samples: (25069, 2440) (25069, 2)


ValueError: Error when checking input: expected dense_171_input to have shape (1068,) but got array with shape (2440,)

In [130]:
print('mean_squared error is:',np.round(model.evaluate(X_val,Y_val,batch_size=50,verbose=True)[1],4)) # predict and evaluate


1704/1704 [==============================] - 0s 176us/step
mean_squared error is: 0.0081


In [66]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_69 (Dense)             (None, 2000)              2334000   
_________________________________________________________________
dropout_52 (Dropout)         (None, 2000)              0         
_________________________________________________________________
dense_70 (Dense)             (None, 1000)              2001000   
_________________________________________________________________
dropout_53 (Dropout)         (None, 1000)              0         
_________________________________________________________________
dense_71 (Dense)             (None, 500)               500500    
_________________________________________________________________
dropout_54 (Dropout)         (None, 500)               0         
_________________________________________________________________
dense_72 (Dense)             (None, 2)                 1002      
Total para

In [115]:
print(np.expand_dims(X,axis=0))
model.predict(X[40:50,:],batch_size=1,verbose=1)

[[[0.         0.94       0.63125798 ... 0.         0.         0.        ]
  [0.         0.92       0.59697557 ... 0.         0.         0.        ]
  [0.         0.92       0.21360583 ... 0.         0.         0.        ]
  ...
  [0.         0.9        0.4727018  ... 0.         0.         0.        ]
  [0.         0.98       0.35843697 ... 0.         0.         0.        ]
  [0.         0.94       0.19086077 ... 0.         0.         0.        ]]]
10/10 [==============================] - 0s 4ms/step


array([[0.3406136 , 0.3621384 ],
       [0.30426335, 0.27991974],
       [0.3125102 , 0.30506206],
       [0.41895407, 0.3680009 ],
       [0.44900405, 0.2485365 ],
       [0.43819833, 0.2445526 ],
       [0.3656872 , 0.4104563 ],
       [0.40235984, 0.34403163],
       [0.48073292, 0.3419884 ],
       [0.4825936 , 0.34046835]], dtype=float32)

In [65]:
print(X.iloc[[6],:].to_numpy())
model.predict(X.iloc[[6],:].to_numpy())

[[   0.    2010.      18.946 ...    0.       0.       0.   ]]


array([[1., 1.]], dtype=float32)

In [61]:
dfg['full']=dfg['taste_full'].apply(lambda x: 1 if x >0 else 0)

In [112]:
to_categorical(Y_train)[:,0].squeeze()

array([0., 0., 0., ..., 0., 0., 1.], dtype=float32)

In [93]:
dir(np.array([1,2,3]))

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [111]:
np.array([[1],[2],[3]]).squeeze()

array([1, 2, 3])

In [172]:
ycol=['points','price']
X = dfg.drop(ycol, axis=1) # Training & Validation data
Y = dfg[ycol]              # Response / Target Variable
### normalize data
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
Y=scaler.fit_transform(Y)
print(Y)

[[0.35       0.        ]
 [0.35       0.00454545]
 [0.35       0.00424242]
 ...
 [0.5        0.00909091]
 [0.5        0.00969697]
 [0.5        0.00636364]]


In [125]:
'taste_almond' in list(dfg.filter(regex='^(?!taste)').columns)

False

In [175]:
from sklearn.linear_model import Lasso
from sklearn.metrics import mean_squared_error
#lasso model
lasso = Lasso()   # instantiate
lasso.fit(X_train, Y_train)                         # fit
# acc_rf = lasso.score(X_val, Y_val)                  # predict + evaluate
y_pred= lasso.predict(X_val)
print(y_pred)
print(Y_val)
mse = [mean_squared_error(Y_val[:,0], y_pred[:,0]),mean_squared_error(Y_val[:,1], y_pred[:,1])]
# print('mean squared error points', str(round(mse[0],6)),'price',str(round(mse[1],6)))
print(mse)

[[87.7903674  23.6830215 ]
 [88.50406557 37.97159438]
 [88.50406557 36.61606759]
 ...
 [87.5406695  24.14633613]
 [88.37310348 33.9500612 ]
 [88.88558613 56.48870397]]
        points  price
72130       90   23.0
47204       82   24.0
93975       82   15.0
66584       91   36.0
47753       87   20.0
...        ...    ...
16629       93   39.0
108966      85   27.0
22246       88   25.0
74697       84   10.0
75556       96  216.0

[25069 rows x 2 columns]


TypeError: '(slice(None, None, None), 0)' is an invalid key

In [136]:
sklearn.linear_model import ElasticNet

array([0.42105263, 0.52631579, 0.68421053, ..., 0.68421053, 0.52631579,
       0.42105263])

In [181]:
from sklearn.linear_model import ElasticNet
from sklearn.metrics import mean_squared_error
#elasticnet model
elas = ElasticNet()   # instantiate
elas.fit(X_train, Y_train)                         # fit
y_pred = elas.predict(X_val)
mse = mean_squared_error(Y_val, y_pred)

print('mean squared error is:', str(round(mse,6)))

mean squared error is: 0.023581


In [150]:
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error
#ridge model
ridge = Ridge()   # instantiate
ridge.fit(X_train, Y_train)                         # fit
y_pred = ridge.predict(X_val)
mse = mean_squared_error(Y_val, y_pred)

print('mean squared error is:', str(round(mse,6)))

mean squared error is: 0.007761


In [158]:
import xgboost as xgb
gbm = xgb.XGBClassifier(max_depth=3, n_estimators=300, learning_rate=0.05)
gbm.fit(X_train, Y_train[:,0])  
y_pred = gbm.predict(X_val)
mse = mean_squared_error(Y_val, y_pred[:,0])

print('mean squared error is:', str(round(mse,6)))

KeyboardInterrupt: 

In [157]:
Y_train[:,0]

array([0.42105263, 0.52631579, 0.68421053, ..., 0.68421053, 0.52631579,
       0.42105263])

In [186]:
[mean_squared_error(Y_val[:,0], y_pred[:,0]),mean_squared_error(Y_val[:,1], y_pred[:,1])]

[0.023469021515864143, 0.023692288424427506]

In [182]:
Y_val[:,0]

array([0.6 , 0.35, 0.25, ..., 0.4 , 0.35, 0.45])

In [183]:
y_pred[:,0]

array([0.42426154, 0.42426154, 0.42426154, ..., 0.42426154, 0.42426154,
       0.42426154])

In [180]:
ycol=['points','temp1']
regex_out_taste='^(?!taste)'
X = dfg.filter(regex=regex_out_taste).drop(ycol, axis=1) # Training & Validation data
Y = dfg[ycol]              # Response / Target Variable
### normalize data
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
X=scaler.fit_transform(X)
Y=scaler.fit_transform(Y)
# print(Y)

print(X.shape, Y.shape)

# Split training set so that we validate on 20% of the data
# Note that our algorithms will never have seen the validation 

np.random.seed(5875) # set random seed for reproducibility

from sklearn.model_selection import train_test_split

X_train, X_val, Y_train, Y_val = \
                train_test_split(X, Y, test_size=0.2)

print('Training Samples:', X_train.shape, Y_train.shape)
print('Validation Samples:', X_val.shape, Y_val.shape)

(125345, 2440) (125345, 2)
Training Samples: (100276, 2440) (100276, 2)
Validation Samples: (25069, 2440) (25069, 2)
